#include <unistd.h>
#include <getopt.h>

#include "sh.h"
#include "defs.h"
#include "dirs.h"
#include "clean.h"
#include "error.h"
#include "message.h"


// Raw strings
static const string help_message {
R"message(
Remove autogenerated files. These files are located in '.cp-build' directory of the working folder.

    Option          Description

    -h              Generates this help message.
    --help

    -w              Directory to be cleaned.
    --working-dir

)message"
};

namespace cptools::clean {

    // Global variables
    static struct option longopts[] = {
       { "help", no_argument, NULL, 'h' },
       { "working-dir", required_argument, NULL, 'w' },
       { 0, 0, 0, 0 }
    };

    // Auxiliary routines
    string usage()
    {
        return "Usage: " NAME " clean [-h] [-w working-dir]";
    }

    string help()
    {
        return usage() + help_message;
    }

    int remove_autogenerated_files(const string& target, ostream& out, ostream& err)
    {
        out << "Cleaning autogenerated files...\n";

        // Localiza o arquivo que armazena os arquivos autogerados
        string build_dir { target + "/" + CP_TOOLS_BUILD_DIR };

        string error;
        auto rc = cptools::sh::is_dir(build_dir, error);

        if (not rc)
        {
            out << message::warning() << " No autogenerated files found!\n";
            return CP_TOOLS_OK;
        }

        // Exclui este diretório
        error = "";
        rc = cptools::sh::remove_dir(build_dir, error);

        if (rc != CP_TOOLS_OK)
        {
            err << message::failure() << " Error removing '" << build_dir << "'\n";
            err << message::trace(error) << '\n';
            return CP_TOOLS_ERROR_CLEAN_DELETE_FILES;
        }

        out << message::success() << '\n';
        return CP_TOOLS_OK;
    }

    // API functions
    int run(int argc, char* const argv[], ostream& out, ostream& err)
    {
        int option = -1;
        string target { "." };

        while ((option = getopt_long(argc, argv, "hw:", longopts, NULL)) != -1)
        {
            switch (option) {
            case 'h':
                out << help() << '\n';
                return 0;

            case 'w':
                target = string(optarg);
                break;

            default:
                err << help() << '\n';
                return CP_TOOLS_ERROR_CLEAN_INVALID_OPTION;
            }
        }

        return remove_autogenerated_files(target, out, err);
    }
}
