#include <map>

#include <unistd.h>
#include <getopt.h>

#include "defs.h"
#include "error.h"

#include "init.h"
#include "clean.h"
#include "gentex.h"
#include "cptools.h"


// Raw strings
static const std::string help_message {
R"message(
Format, test and pack competitive programming problems.

    Action              Description

    init                Generate template files on current directory.
    clean               Remove autogenerated files.
    gentext             Generate a LaTeX file from the problem description. 
)message"
};

static const std::string version_header { NAME " " VERSION "\n" };

static const std::string version_body { 
R"body(License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Edson Alves.)body"
};


namespace cptools {

    // Global variables
    std::map<std::string, int (*)(int, char *const [], std::ostream&, std::ostream&)> commands {
    //    { "init", init },
    //    { "clean", clean },
    //    { "gentex", gentex },
    };

    static struct option longopts[] = {
       { "help", no_argument, NULL, 'h' },
       { "version", no_argument, NULL, 'v' },
       { 0, 0, 0, 0 }
    };


    // Auxiliary routines
    std::string usage()
    {
        return "Usage: " NAME " [-h] [-v] action";
    }

    std::string help()
    {
        return usage() + help_message;
    }

    std::string version()
    {
        return version_header + version_body;
    }

    // API functions
    int run(int argc, char* const argv[], std::ostream& out, std::ostream& err)
    {
        if (argc < 2)
        {
            err << usage() << '\n';
            return CP_TOOLS_ERROR_MISSING_ARGUMENT;
        }

        auto command = argv[1];

        for (const auto& [cmd, exec] : commands)
        {
            if (cmd == command)
                return exec(argc, argv, std::cout, std::cerr);
        }

        int option = -1;

        while ((option = getopt_long(argc, argv, "hv", longopts, NULL)) != -1)
        {
            switch (option) {
            case 'v':
                out << version() << '\n';
                return CP_TOOLS_OK;
            
            case 'h':
                out << help() << '\n';
                return CP_TOOLS_OK;

            default:
                err << help() << '\n';
                return CP_TOOLS_ERROR_INVALID_PARAMETER;
            }
        }

        out << "no options = " << argv[1] << "\n";
        return CP_TOOLS_OK;
    }
}
